allowBuilds:
  '@firebase/util': false
  '@sentry/cli': false
  core-js: false
  protobufjs: false
  unrs-resolver: false

nodeLinker: hoisted

overrides:
  react-native-svg: 15.12.1
  react-native-webview: 13.15.0
  protobufjs: ^7.5.9

patchedDependencies:
  react-native-callkeep: patches/react-native-callkeep.patch

storeDir: /home/eazy/.local/share/pnpm/store/v10
